Lab.EF/Lab.EF.MVC/Models/CategoriasView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab.EF.MVC.Models
{
    public class CategoriasView
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        [RegularExpression("^[^0-9]+$", ErrorMessage = "El nombre de categorias no acepta valores numericos")]
        [StringLength(15)]
        public string Nombre { get; set; }
        [RegularExpression("^[^0-9]+$", ErrorMessage = "La descripcion no acepta valores numericos")]
        public string Descripcion { get; set; }
    }
}

Lab.EF/Lab.EF.MVC/Models/UsuariosView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab.EF.MVC.Models
{
    public class UsuariosView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public AddressView Address { get; set; }
        public string Phone { get; set; }
        public string WebSite { get; set; }
    }
    public class AddressView
    {
        public string Street { get; set; }
        public string Suite { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }
        public GeoView Geo { get; set; }
    }
    public class GeoView
    {
        public string Lat { get; set; }
        public string Lng { get; set; }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/ApiPublicaController.cs
using Lab.EF.MVC.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class ApiPublicaController : Controller
    {
        private readonly string url = "https://jsonplaceholder.typicode.com/users";
        private HttpClient httpClient = new HttpClient();

        // GET: ApiPublica
        public async Task<ActionResult> ConsumirApiPublica()
        {
            var respuesta = await httpClient.GetStringAsync(url);
            var usuariosView = JsonConvert.DeserializeObject<UsuariosView[]>(respuesta);
            return View(usuariosView);
        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/CategoriasController.cs
using Lab.EF.Entidades;
using Lab.EF.Logica;
using Lab.EF.Logica.Categorias;
using Lab.EF.MVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class CategoriasController : Controller
    {

        private CategoriasLogica _categoriasLogica = new CategoriasLogica();
        private CategoriasView _categoriasView = new CategoriasView();

        public ActionResult ObtenerCategorias()
        {
            try
            {
                List<CategoriasDto> categoriasLogicaLista = _categoriasLogica.ObtenerTodos();
                return View(categoriasLogicaLista);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorVista","Error");
            }
        }

        public ActionResult Insertar()
        {
            try
            {
                return View("InsertarModificarCategoria", new CategoriasView());
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorVista","Error");
            }
        }

        public ActionResult Modificar(int id)
        {
            try
            {
                Categories entidad = _categoriasLogica.ObtenerUno(id);
                CategoriasView view = new CategoriasView()
                {
                    Id = entidad.CategoryID,
                    Nombre = entidad.CategoryName,
                    Descripcion = entidad.Description
                };
                return View("InsertarModificarCategoria", view);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorVista", "Error");
            }
        }

        [HttpPost]
        public ActionResult InsertarModificarCategoria(CategoriasView view)
        {
            if (ModelState.IsValid)
            {
                if (view.Id > 0)
                {
                    _categoriasLogica.Modificar(new CategoriasDto
                    {
                        Id = view.Id,
                        Nombre = view.Nombre,
                        Descripcion = view.Descripcion,
                    });
                }
                else
                {
                    _categoriasLogica.Add(new CategoriasDto
                    {
                        Nombre = view.Nombre,
                        Descripcion = view.Descripcion,
                    });
                }

                return RedirectToAction("ObtenerCategorias");
            }
            else
            {
                if (view.Id > 0)
                {
                    return View("InsertarModificarCategoria");
                }
                else
                {
                    return View("InsertarModificarCategoria", new CategoriasView());
                }
            }
        }

        public ActionResult EliminarCategoria(int id)
        {
            try
            {
                Categories entidad = _categoriasLogica.ObtenerUno(id);
                CategoriasView view = new CategoriasView()
                {
                    Id = entidad.CategoryID,
                    Nombre = entidad.CategoryName,
                    Descripcion = entidad.Description
                };
                return View(view);
            }
            catch (DbUpdateException)
            {
                return RedirectToAction("EliminarSinPermiso", "Error");
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorVista", "Error");
            }
        }

        [HttpPost]
        public ActionResult EliminarCategoria(CategoriasView categoriasView)
        {
            try
            {              
                _categoriasLogica.Eliminar(categoriasView.Id);
                return RedirectToAction("ObtenerCategorias");
            }
            catch (DbUpdateException)
            {
                return RedirectToAction("EliminarSinPermiso", "Error");
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorVista", "Error");
            }
        }

        public ActionResult VolverPaginaPrincipal()
        {
            return RedirectToAction("ObtenerCategorias");
        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class ErrorController : Controller
    {
        public ActionResult ErrorVista()
        {
            return View();
        }

        public ActionResult EliminarSinPermiso() 
        {
            return View();
        }

        public ActionResult UrlConLetras()
        {
            return View();
        }
    }
}

Lab.EF/Lab.EF.MVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Lab.EF.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string path)
        {
             return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab.EF/Lab.EF.MVC/Views/ApiPublica/ConsumirApiPublica.cshtml
@model Lab.EF.MVC.Models.UsuariosView[]
@{
    ViewBag.Title = "Listado de Usuarios";
}

<h2>Listado de Usuarios</h2>

<table class="table table-striped">
    <thead>
        <tr class="table-primary">
            <td scope="col">Nombre</td>
            <td scope="col">Usuario</td>
            <td scope="col">Email</td>
            <td scope="col">Apartamento</td>
            <td scope="col">Cuidad</td>
            <td scope="col">Calle</td>
            <td scope="col">Telefono</td>
            <td scope="col">Sitio Web</td>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.UserName</td>
            <td>@item.Email</td>
            <td>@item.Address.Suite</td>
            <td>@item.Address.City</td>
            <td>@item.Address.Street</td>
            <td>@item.Phone</td>
            <td>@item.WebSite</td>
        </tr>
    }
</table>

Lab.EF/Lab.EF.MVC/Views/Categorias/EliminarCategoria.cshtml
@model Lab.EF.MVC.Models.CategoriasView
@{
    ViewBag.Title = "Eliminar Categoria";
}

<h2>Eliminar Categoria</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(c => c.Id)

    <div class="form-group">
         @Html.LabelFor(c => c.Nombre)
         <br />
         @Html.TextBoxFor(c => c.Nombre, new { disabled = "disabled" })
    </div>
    <br />
    <div class="form-group">
         @Html.LabelFor(c => c.Descripcion)
         <br />
         @Html.TextAreaFor(c => c.Descripcion, new { disabled = "disabled" })
    </div>
    <br />
     <input class="btn btn-danger" type="submit" value="Eliminar" />
     <input class="btn btn-primary" type="button" value="Cancelar"
            onclick="location.href='@Url.Action("VolverPaginaPrincipal","Categorias")'" />
 }

Lab.EF/Lab.EF.MVC/Views/Categorias/Index.cshtml
@model List<Lab.EF.Logica.Categorias.CategoriasDto>
@{
    ViewBag.Title = "Categorias";
}

<h1>Listado de Categorias</h1>

<table class="table-responsive">

    <tr>
        <td>Nombre</td>
        <td>Descripcion</td>
    </tr>

    @foreach (var categorias in Model)
    {
        <tr>
            <td>@categorias.Nombre</td>
            <td>@categorias.Descripcion</td>
        </tr>

    }

    <li>@Html.ActionLink("Insertar Categoria", "InsertarCategoria", "Categorias")</li>
</table>

Lab.EF/Lab.EF.MVC/Views/Categorias/InsertarModificarCategoria.cshtml
@model Lab.EF.MVC.Models.CategoriasView
@{
    ViewBag.Title = "Formulario de Categoria";
}

<h1>Formulario de Categoria</h1>

@using (Html.BeginForm("InsertarModificarCategoria", "Categorias", FormMethod.Post))
{

    @Html.HiddenFor(c => c.Id)

    <div class="form-group">
        @Html.LabelFor(c => c.Nombre)
        @Html.TextBoxFor(c => c.Nombre, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Nombre, "", new { @class = "text-danger" })
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(c => c.Descripcion)
        @Html.TextBoxFor(c => c.Descripcion, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Descripcion, "", new { @class = "text-danger" })
    </div>
    <br />
    <input class="btn btn-primary" type="submit" value="Aceptar" />
    <input class="btn btn-danger" type="button" value="Cancelar"
           onclick="location.href='@Url.Action("VolverPaginaPrincipal","Categorias")'" />
}

Lab.EF/Lab.EF.MVC/Views/Categorias/ObtenerCategorias.cshtml
@model List<Lab.EF.Logica.Categorias.CategoriasDto>
@{
    ViewBag.Title = "Categorias";
}

<h1>Listado de Categorias</h1>

<table class="table table-striped">

    <tr>
        @Html.ActionLink("Insertar Categoria", "Insertar", "Categorias"
          , new { @class = "btn btn-success" })
    </tr>
    <br />
    <br />
    <thead>
        <tr class="table-primary">
            <td scope="col">Nombre</td>
            <td scope="col">Descripcion</td>
            <td scope="col">Eliminar</td>
            <td scope="col">Modificar</td>
        </tr>
    </thead>

    @foreach (var categorias in Model)
    {
        <tr>
            <td>@categorias.Nombre</td>
            <td>@categorias.Descripcion</td>
            <td scope="col">
                @Html.ActionLink("Eliminar", "EliminarCategoria",
                new { Id = categorias.Id }, new { @class = "btn btn-danger" })
            </td>
            <td scope="col">
                @Html.ActionLink("Modificar", "Modificar",
                new { Id = categorias.Id }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }
</table>

Lab.EF/Lab.EF.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Lab.EF/Lab.EF.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Lab.EF/Lab.EF.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Categorias", "ObtenerCategorias", "Categorias", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("API Publica", "ConsumirApiPublica", "ApiPublica", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>